- name: awx
  hosts: all
  become: yes
  become_method: sudo
  remote_user: '{{admin_username}}'
  
  roles:
    # - { role: common , tags: common }
    # - { role: postgresql , tags: postgresql }
    - { role: awx , tags: awx }
